version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER:root
      - MYSQL_PASSWORD:root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops
    volumes:
      - db_vol:/var/lib/mysqldb
    networks:
      - my_network

  devops_app:
    build: ./
    image: hedilouhichi-5ds
    restart: unless-stopped
    ports:
      - 8082:8082
    depends_on:
      - mysqldb
    networks:
      - my_network

networks:
  my_network:

volumes:
  db_vol:
