version: "3.8"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops

    volumes:
      - db_vol:/var/lib/mysqldb
    networks:
      - my_network

  devops_app:
    image: eyaferchichi/devopsproject-2.1  # Utilisez l'image correcte pour votre application backend
    container_name: demo
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/devops?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
      - 8082:8082
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    depends_on:
      - mysqldb
    networks:
      - my_network

  front_app:
    build: ./DevOps_Project_Front
    container_name: demo-ui
    image: front
    restart: unless-stopped
    ports:
      - 4200:80
    networks:
      - my_network

networks:
  my_network:

volumes:
  db_vol:
  .m2:
