version: "3.8"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER:root
      - MYSQL_PASSWORD:root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops
    volumes:
      - db_vol:/var/lib/mysqldb
    networks:
      - my_network

  devops_app:
    build: ./
    image: hedilouhichi-5ds
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/devops?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC 
    ports:
      - 8082:8082
    volumes:
      -  .m2:/root/.m2
    stdin_open: true
    tty: true
    depends_on:
      - mysqldb
    networks:
      - my_network
  front_app:
    build: ./DevOps_Project_Front
    image: front
    restart: unless-stopped
    ports:
      - 4200:80
    networks:
      - my_network


networks:
  my_network:

volumes:
  db_vol:
  .m2:
